name: Submission Request

on:
  issues:
    types:
      - opened

jobs:
  submission-request:
    if: contains(github.event.issue.labels.*.name, 'submitted')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await octokit.rest.repos.createDispatchEvent({
              owner: 'fly-hiring',
              repo: 'submission-hub',
              event_type: 'submission_request',
              client_payload: {
                repo: context.repo.fullName || `${context.repo.owner}/${context.repo.repo}`
              }
            });
